version: "3.9"
services:
  cdr-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - cdr-server-network

  db:
    image: "postgres:12.9"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=db_cdr"
    ports:
      - "5432:5432"
    networks:
      - cdr-server-network

  prometheus:
    image: prom/prometheus:v2.35.0
    restart: unless-stopped
    depends_on:
      - cdr-server
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    networks:
      - cdr-server-network

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    restart: unless-stopped
    user: root
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug
    networks:
      - cdr-server-network

networks:
  cdr-server-network: